mysite/main/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('main/', include('main.urls')),
    path('register/', include('register.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('main/', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('register/', include('register.urls')),
    path('admin/', admin.site.urls),
]

mysite/main/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
was_published_recently.admin_order_field = 'pub_date'
was_published_recently.boolean = True
was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'main/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'main/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))

mysite/main/templates/main/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'main:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/main/templates/main/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'main:detail' question.id %}">{{ question.question_text }}</a></li>    
    {% endfor %}
    </ul>
{% endif %}

    <section>
    <header>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        
        <title>
            solarPV R&D
        </title>
    </header>

    <body>
    <div class="container">
       <div class="container">
           <img src="../static/main/solarPvLogo.png" href="/main">
           
       </div> 
        <nav>
            <ul>
                <li><a href = "../main"> Main </a></li>
                <li><a> Racks & Trackers </a></li>
                <li><a> PV Module </a></li>
                <li><a> PV Systems </a></li>
                <li><a> Data Analytics </a></li>
                <li><a> Cybersecurity </a></li>
                <li><a href ="../dashboard"> Dashboard </a></li>
            </ul>
        </nav>
    </div>
    <div class="container">
        <div class="leftNav"> 
                    <h1> <a href="../register">Register</a> | <a>Login</a> </h1>
            <h2>PV Module</h2>
            <ul>
                <li>Testing & Certification</li>
                <li>PV Rating</li>
            </ul>
            <h2>PV System Performance</h2>
            <ul>
                <li>Monitoring & Inspection</li>
                <li>Performance Analysis</li>
                <li>Compare system</li>
                <li>Certification</li>
            </ul>
            <h2>Data Analytics</h2>
            <ul>
                <li>Module lifetime prediction</li>
                <li>Energy Prediction</li>
            </ul>
            <h2>Cybersecurity and Smart Grid Technologies</h2>
            <h2>Solar PV University</h2>

        </div>
        <div class="main">
            <p><i>Feature Contents</i></p>
        </div>
        <div class="rightNav">
            <h1>News & Events</h1>
            <p>PhotoVoltaic Technical Conference to take place in Marseille, France from 26 to 28 April 2017</p>
            <p>Trump is next US president</p>
            <p>Syrian forces recapture Aleppo</p>
            <p>Senate votes on SCOTUS nominee</p>
        </div>
    </div>

    <footer id="footer">
        <p><b>SolarPV</b></p>
        <p>Address, Phone, Email, Website</p> 
        <p><a>Site Map</a> | <a>Terms & Conditions</a> | <a>Privacy Policy</a> | <a>About Us</a></p>
        <p style="align-content: right;">@ 2019 All Rights Reserved</p>
    </footer>

</body>

</section>

mysite/main/templates/main/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'main:detail' question.id %}">Vote again?</a>