mysite/dashboard/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('dash', views.IndexView.as_view(), name='dash'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('main/', include('main.urls')),
    path('register/', include('register.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('main/', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('register/', include('register.urls')),
    path('admin/', admin.site.urls),
]

mysite/dashboard/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
was_published_recently.admin_order_field = 'pub_date'
was_published_recently.boolean = True
was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/dashboard/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'dashboard/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'dashboard/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'dashboard/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'dashboard/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('dashboard:results', args=(question.id,)))

mysite/dashboard/templates/dashboard/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dashboard:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/dashboard/templates/dashboard/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}">

    <header>        
        <title>
            SolarPV Dashboard 
        </title>
    </header>

<!------------>
<!--Nav Bar-->
<!------------>
    <div class="container">
       <div class="container">
           <img src="../static/dashboard/solarPvLogo.png" href="/main">          
       </div> 
        <nav>
            <ul>
                <li><a href = "../main"> Main </a></li>
                <li><a> Racks & Trackers </a></li>
                <li><a> PV Module </a></li>
                <li><a> PV Systems </a></li>
                <li><a> Data Analytics </a></li>
                <li><a> Cybersecurity </a></li>
                <li><a href ="../dashboard"> Dashboard </a></li>
            </ul>
        </nav>
    </div>

<!---------------->
<!--Client Form-->
<!---------------->
<section>
<body>
    <div id="container">
        <div id="main">
            <form>
            <h1>Client information</h1> <br>
            <input type="text" name="clientCode" placeholder="Client Code" required><br>
            <input type="text" name="clientName" placeholder="Client Name" required><br>
            <input type="text" name="clientType" placeholder= "ClientType"><br>
            <input type="submit" value="Submit">
        </form>

        </div>
    </div>
</body>
</section>

<!------------------>
<!--Location Form-->
<!------------------>
<section>
<body>
    <div id="container">    
        <div id="main">
            <form>
                <h1>Location information</h1> <br>
                <input type="text" name="clientID" placeholder="ClientID" required><br>
                <input type="text" name="address1" placeholder="Address1" required><br>
                <input type="text" name="address2" placeholder="Address2"><br>
                <input type="text" name="city" placeholder="City"><br>
                <input type="text" name="state" placeholder="State"><br>
                <input type="text" name="postalCode" placeholder="Zip Code"><br>
                <input type="text" name="country" placeholder="Country"><br>
                <input type="text" name="phoneNumber" placeholder="Phone Number"><br>
                <input type="text" name="faxNumber" placeholder="Fax Number"><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</section>

<!---------------->
<!--Product Form-->
<!---------------->
<section>
<body>
    <div id="container">    
        <div id="main">
            <form>
                <h1>Product information</h1> <br>
                <input type="text" name="modelNum" placeholder="Model Number" required><br>
                <input type="text" name="prodName" placeholder="Name" required><br>
                <input type="text" name="cellTechnology" placeholder="Cell Technology"><br>
                <input type="text" name="cellManufacturer" placeholder="Cell Manufacturer"><br>
                <input type="text" name="numberOfCells" placeholder="Number of Cells"><br>
                <input type="text" name="numberCellsSeries" placeholder="Number of Cells in Series"><br>
                <input type="text" name="numberSeriesStr" placeholder="Number of Series of Strings"><br>
                <input type="text" name="numberDiodes" placeholder="Number of Diodes"><br>
                <input type="text" name="productLength" placeholder="Product Length"><br>
                <input type="text" name="productWidth" placeholder="Product Width"><br>
                <input type="text" name="superstrateType" placeholder="Superstrate Type"><br>
                <input type="text" name="superstrateManufacturer" placeholder="Superstrate Manufacturer"><br>
                <input type="text" name="substrateType" placeholder="Substrate Type"><br>
                <input type="text" name="SubstrateManufacturer" placeholder="Substrate Manufacturer"><br>
                <input type="text" name="frameType" placeholder="Frame Type"><br>
                <input type="text" name="frameAdhesive" placeholder="Frame Adhesive"><br>
                <input type="text" name="encapsulantType" placeholder="Encapsulant Type"><br>
                <input type="text" name="encapsulantManufacturer" placeholder="Encapsulant Manufacturer"><br>
                <input type="text" name="junctionBoxType" placeholder="Junction Box Type"><br>
                <input type="text" name="junctionBoxManufacturer" placeholder="Junction Box Manufacturer"><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>

</body>
</section>

<!---------------------->
<!--Test Standard Form-->
<!---------------------->
<section>
<body>
    <div id="container">
        <div id="main">
            <form>
                <h1>Test Standard information</h1> <br>
                <input type="text" name="testStandardID" placeholder="Test Standard ID" required><br>
                <input type="text" name="testStandardName" placeholder="Name" required><br>
                <input type="text" name="testStandardDesc" placeholder="Description" required><br>
                <input type="text" name="testStandardPubDate" placeholder="Published Date" required><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</section>

<!-------------------->
<!--Certificate Form-->
<!-------------------->
<section>
<body>
    <div id="container">
        <div id="main">
            <form>
                <h1>Certificate information</h1> <br>
                <input type="text" name="certID" placeholder="Certificate ID" required><br>
                <input type="text" name="certNumber" placeholder="Certificate Number" required><br>
                <input type="text" name="locationID" placeholder="Location id" required><br>
                <input type="text" name="reportNumber" placeholder="Report number" required><br>
                <input type="text" name="contactID" placeholder="Contact ID" required><br>
                <input type="text" name="testStandardID" placeholder="Test Standdard ID" required><br>
                <input type="text" name="productID" placeholder="Product ID" required><br>
                <input type="text" name="certIssueDate" placeholder="Certificate Issue Date" required><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</section>

<!---------->
<!--FOOTER-->
<!---------->
<section>
    <div class="container">
        <footer id="footer">
            <p><b>SolarPV</b></p>
            <p>Address, Phone, Email, Website</p> 
            <p><a>Site Map</a> | <a>Terms & Conditions</a> | <a>Privacy Policy</a> | <a>About Us</a></p>
            <p style="align-content: right;">@ 2020 All Rights Reserved</p>
        </footer>
    </div>
</section>

</html>

mysite/dashboard/templates/dashboard/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'dashboard:detail' question.id %}">Vote again?</a>